NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts\ca.agri.landregistry.gov.in-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts\ca.agri.landregistry.gov.in-cert.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts\ca.agri.landregistry.gov.in-cert.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts\ca.agri.landregistry.gov.in-cert.pem
    OrganizationalUnitIdentifier: orderer
