version: '3.7'

networks:
  land_registry:
    name: land_registry_network

volumes:
  orderer0.orderer.landregistry.gov.in:
  orderer1.orderer.landregistry.gov.in:
  orderer2.orderer.landregistry.gov.in:
  orderer3.orderer.landregistry.gov.in:
  orderer4.orderer.landregistry.gov.in:
  peer0.revenue.landregistry.gov.in:
  peer1.revenue.landregistry.gov.in:
  peer0.registration.landregistry.gov.in:
  peer1.registration.landregistry.gov.in:
  peer0.bank.landregistry.gov.in:
  peer1.bank.landregistry.gov.in:
  peer0.govtech.landregistry.gov.in:
  peer1.govtech.landregistry.gov.in:
  peer0.public.landregistry.gov.in:
  peer0.agri.landregistry.gov.in:

services:
  # Orderer Nodes (Raft Consensus)
  orderer0.orderer.landregistry.gov.in:
    container_name: orderer0.orderer.landregistry.gov.in
    image: hyperledger/fabric-orderer:2.5
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer0.orderer.landregistry.gov.in:9443
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: orderer
    volumes:
      - ../organizations/ordererOrganizations/orderer.landregistry.gov.in/orderers/orderer0.orderer.landregistry.gov.in/msp:/var/hyperledger/orderer/msp
      - ../organizations/ordererOrganizations/orderer.landregistry.gov.in/orderers/orderer0.orderer.landregistry.gov.in/tls:/var/hyperledger/orderer/tls
      - orderer0.orderer.landregistry.gov.in:/var/hyperledger/production/orderer
      - ../channel-artifacts:/var/hyperledger/channel-artifacts
    ports:
      - 7050:7050
      - 7053:7053
      - 9443:9443
    networks:
      - land_registry

  orderer1.orderer.landregistry.gov.in:
    container_name: orderer1.orderer.landregistry.gov.in
    image: hyperledger/fabric-orderer:2.5
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7051
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7054
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer1.orderer.landregistry.gov.in:9444
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: orderer
    volumes:
      - ../organizations/ordererOrganizations/orderer.landregistry.gov.in/orderers/orderer1.orderer.landregistry.gov.in/msp:/var/hyperledger/orderer/msp
      - ../organizations/ordererOrganizations/orderer.landregistry.gov.in/orderers/orderer1.orderer.landregistry.gov.in/tls:/var/hyperledger/orderer/tls
      - orderer1.orderer.landregistry.gov.in:/var/hyperledger/production/orderer
      - ../channel-artifacts:/var/hyperledger/channel-artifacts
    ports:
      - 7051:7051
      - 7054:7054
      - 9444:9444
    networks:
      - land_registry

  orderer2.orderer.landregistry.gov.in:
    container_name: orderer2.orderer.landregistry.gov.in
    image: hyperledger/fabric-orderer:2.5
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7052
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7055
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer2.orderer.landregistry.gov.in:9445
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: orderer
    volumes:
      - ../organizations/ordererOrganizations/orderer.landregistry.gov.in/orderers/orderer2.orderer.landregistry.gov.in/msp:/var/hyperledger/orderer/msp
      - ../organizations/ordererOrganizations/orderer.landregistry.gov.in/orderers/orderer2.orderer.landregistry.gov.in/tls:/var/hyperledger/orderer/tls
      - orderer2.orderer.landregistry.gov.in:/var/hyperledger/production/orderer
      - ../channel-artifacts:/var/hyperledger/channel-artifacts
    ports:
      - 7052:7052
      - 7055:7055
      - 9445:9445
    networks:
      - land_registry

  # CouchDB Instances
  couchdb.revenue.peer0:
    container_name: couchdb.revenue.peer0
    image: couchdb:3.3
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 5984:5984
    networks:
      - land_registry

  couchdb.registration.peer0:
    container_name: couchdb.registration.peer0
    image: couchdb:3.3
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 6984:5984
    networks:
      - land_registry

  couchdb.bank.peer0:
    container_name: couchdb.bank.peer0
    image: couchdb:3.3
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 7984:5984
    networks:
      - land_registry

  # Revenue Department Peers
  peer0.revenue.landregistry.gov.in:
    container_name: peer0.revenue.landregistry.gov.in
    image: hyperledger/fabric-peer:2.5
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=peer0.revenue.landregistry.gov.in
      - CORE_PEER_ADDRESS=peer0.revenue.landregistry.gov.in:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.revenue.landregistry.gov.in:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.revenue.landregistry.gov.in:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.revenue.landregistry.gov.in:7051
      - CORE_PEER_LOCALMSPID=OrgRevenueMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.revenue.peer0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_OPERATIONS_LISTENADDRESS=peer0.revenue.landregistry.gov.in:9446
      - CORE_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: peer node start
    volumes:
      - ../organizations/peerOrganizations/revenue.landregistry.gov.in/peers/peer0.revenue.landregistry.gov.in:/etc/hyperledger/fabric
      - peer0.revenue.landregistry.gov.in:/var/hyperledger/production
    depends_on:
      - couchdb.revenue.peer0
    ports:
      - 7051:7051
      - 9446:9446
    networks:
      - land_registry

  peer1.revenue.landregistry.gov.in:
    container_name: peer1.revenue.landregistry.gov.in
    image: hyperledger/fabric-peer:2.5
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=peer1.revenue.landregistry.gov.in
      - CORE_PEER_ADDRESS=peer1.revenue.landregistry.gov.in:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.revenue.landregistry.gov.in:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.revenue.landregistry.gov.in:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.revenue.landregistry.gov.in:8051
      - CORE_PEER_LOCALMSPID=OrgRevenueMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_OPERATIONS_LISTENADDRESS=peer1.revenue.landregistry.gov.in:9447
      - CORE_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: peer node start
    volumes:
      - ../organizations/peerOrganizations/revenue.landregistry.gov.in/peers/peer1.revenue.landregistry.gov.in:/etc/hyperledger/fabric
      - peer1.revenue.landregistry.gov.in:/var/hyperledger/production
    ports:
      - 8051:8051
      - 9447:9447
    networks:
      - land_registry

  # Registration Department Peers
  peer0.registration.landregistry.gov.in:
    container_name: peer0.registration.landregistry.gov.in
    image: hyperledger/fabric-peer:2.5
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=peer0.registration.landregistry.gov.in
      - CORE_PEER_ADDRESS=peer0.registration.landregistry.gov.in:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.registration.landregistry.gov.in:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.registration.landregistry.gov.in:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.registration.landregistry.gov.in:9051
      - CORE_PEER_LOCALMSPID=OrgRegistrationMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.registration.peer0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_OPERATIONS_LISTENADDRESS=peer0.registration.landregistry.gov.in:9448
      - CORE_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: peer node start
    volumes:
      - ../organizations/peerOrganizations/registration.landregistry.gov.in/peers/peer0.registration.landregistry.gov.in:/etc/hyperledger/fabric
      - peer0.registration.landregistry.gov.in:/var/hyperledger/production
    depends_on:
      - couchdb.registration.peer0
    ports:
      - 9051:9051
      - 9448:9448
    networks:
      - land_registry

  # Bank Peers
  peer0.bank.landregistry.gov.in:
    container_name: peer0.bank.landregistry.gov.in
    image: hyperledger/fabric-peer:2.5
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=peer0.bank.landregistry.gov.in
      - CORE_PEER_ADDRESS=peer0.bank.landregistry.gov.in:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.bank.landregistry.gov.in:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.bank.landregistry.gov.in:12051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.bank.landregistry.gov.in:11051
      - CORE_PEER_LOCALMSPID=OrgBankMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.bank.peer0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_OPERATIONS_LISTENADDRESS=peer0.bank.landregistry.gov.in:9449
      - CORE_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: peer node start
    volumes:
      - ../organizations/peerOrganizations/bank.landregistry.gov.in/peers/peer0.bank.landregistry.gov.in:/etc/hyperledger/fabric
      - peer0.bank.landregistry.gov.in:/var/hyperledger/production
    depends_on:
      - couchdb.bank.peer0
    ports:
      - 11051:11051
      - 9449:9449
    networks:
      - land_registry

  # CLI tool for manual commands
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.5
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.revenue.landregistry.gov.in:7051
      - CORE_PEER_LOCALMSPID=OrgRevenueMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/revenue.landregistry.gov.in/peers/peer0.revenue.landregistry.gov.in/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/revenue.landregistry.gov.in/peers/peer0.revenue.landregistry.gov.in/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/revenue.landregistry.gov.in/peers/peer0.revenue.landregistry.gov.in/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/revenue.landregistry.gov.in/users/Admin@revenue.landregistry.gov.in/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
      - ../chaincode:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode
      - ../channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - peer0.revenue.landregistry.gov.in
      - peer0.registration.landregistry.gov.in
      - peer0.bank.landregistry.gov.in
    networks:
      - land_registry
